### ISSUE TITLE
Doc - Improve DynamicArray slicing info

### ISSUE THREAD

**Issue by cusma** [algorandfoundation/puya#298]
### Subject of the issue

The `__getitem__` dunder of `DynamicArrays` specifies `slice` as supported input:

```python
def __getitem__(self, index: algopy.UInt64 | int | slice) -> _TArrayItem: ...
```

But it is unclear how/if slicing is supported.

It would be useful to provide more info and examples about working with DynamicArrays and StaticArrays when it comes to common Python operations (e.g. slicing).

### Expected behaviour

Let's say I have a `uint64[]` and I want to slice it using a `arc4.UInt64` as slicing index (`idx`).

I was expecting something like this to compile:

```python
slice = unit64_dyn_array[0, idx]
````

### Actual behaviour

Not supported

**Comment by aorumbayev** [comment]
@daniel-makerx @achidlow if i understand this correctly this might not be supported any time soon due to avm constraints? Would an extra note under dynamicbytes in arc4 section to state that slicing isn't supported suffice? Alternatively we can add extra record to the section on https://algorandfoundation.github.io/puya/lg-unsupported-python-features.html

**Comment by CiottiGiorgio** [comment]
Also, in the current state a slice operation returns an object that is the type of the elements contained?
Wouldn't a slice still return an array of elements of the same type?

**Comment by daniel-makerx** [comment]
This is an error in the stubs interface, slice is not currently supported on ARC4 container types. Will put in a fix to remove that from the interface
